accfg: Add scf for loop state tracing
KULeuven-MICAS/snax-mlir pull request #127
Opened 2024-05-15 16:41 UTC by AntonLydike

This was fun!

2024-05-15 16:52 UTC, AntonLydike commented
Whyyyyyyy 88 chars line limit? Are y'all using 80s terminals or what?

2024-05-16 10:36 UTC, jorendumoulin reviewed
While this looks very impressive, I've looked at this for a bit, but I struggle to understand some things:
- is `_walk` an appropriate name for this function? it does more than walking right. Does it create the def-use chain from acc.setup calls? If so, then the filename `convert_linalg_to_acc` is maybe a bit outdated and should be broader in scope?
- What is the `MarkedSSAValue`? What does it do that the base classe `SSAValue` cannot handle and why is it needed here?

2024-05-16 10:38 UTC, AntonLydike commented on compiler/transforms/convert_linalg_to_acc.py
> +                    # Mathieu did not approve
Yes

2024-05-16 10:39 UTC, AntonLydike commented on tests/filecheck/transforms/accfg-trace-states.mlir
> +//                      ^^                                                                ^^^^^^^^^^^^^           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
I've been experimenting with making filechecks more human understandable, and especially help debug failures when things break later. Thanks for the feedback, this is a good data point!

2024-05-16 12:05 UTC, JosseVanDelm requested changes
This looks very good, but from the code it's taking me a lot of time to understand what is actually happening. Can we discuss this in person maybe?

2024-05-16 14:19 UTC, AntonLydike commented on tests/filecheck/transforms/accfg-trace-states.mlir
> +// CHECK-NEXT:    %thing, %thing_1 = "scf.if"(%cond_1) ({
I think this is xDSL trying to be smart in guessing variable names at some point in the rewriting process

2024-05-20 08:57 UTC, AntonLydike commented on compiler/transforms/convert_linalg_to_acc.py
> +                    updated_accelerators = [
I added a comment `create a list of all accelerator names that were updated. This lists order is important.`

2024-05-20 09:24 UTC, AntonLydike commented on compiler/transforms/convert_linalg_to_acc.py
> +                            )
Added comment to elaborate on what I mean by unusual

2024-05-20 09:25 UTC, AntonLydike commented on compiler/transforms/convert_linalg_to_acc.py
> +                            "Anton was too lazy to implement this edge case."
I added a bit more context in a comment here. Yes, this will be a new fix for the next PR. I don't think we need a separate pass for this though?

2024-05-20 09:25 UTC, AntonLydike commented on compiler/transforms/convert_linalg_to_acc.py
> +                    ]
Done! Added two tests!

2024-05-20 09:26 UTC, AntonLydike commented on compiler/transforms/convert_linalg_to_acc.py
> +                    # add changes states as yield ops in the loop
Fixed in a comment overhaul!

2024-05-20 09:26 UTC, AntonLydike commented on compiler/transforms/convert_linalg_to_acc.py
> +                    # Mathieu did not approve
I put more info in the comments

2024-05-27 13:50 UTC, JosseVanDelm commented on compiler/transforms/convert_linalg_to_acc.py
> +                    updated_accelerators = [
Cool!

2024-05-27 14:06 UTC, JosseVanDelm approved these changes
Nice!

2024-05-27 14:09 UTC, merged